spring:
  security: 
    # @see https://docs.spring.io/spring-security/site/docs/current/reference/html5/  
    oauth2:
      client:
        registration:
          google:
            api-key: 
            client-id: 
            client-secret: 
            scope: 
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
          facebook:
            client-id: 
            client-secret: 
            scope: 
              - email
              - public_profile
looseboxes:
  spring:
    oauth2:
      google:
        # This property is dependent on property: spring.security.oauth2.client.registration.google.api-key
        user-info-uri: https://people.googleapis.com/v1/people/me?personFields=emailAddresses,genders,metadata,names,phoneNumbers,photos,urls&key=${spring.security.oauth2.client.registration.google.api-key}   
      facebook:
        user-info-uri: https://graph.facebook.com/v8.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250),gender,birthday
